/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import java.awt.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.bean.Especie;
import model.bean.Pet;
import model.bean.Usuario;
import model.dao.EspecieDAO;
import model.dao.PetDAO;

/**
 *
 * @author nicol
 */
public class CadastroPet extends javax.swing.JInternalFrame {
    //Variavel para manter o usuario logado
    private Usuario usuarioLogado;
    
    /**
     * Creates new form CadastroPet
     */
    
    public CadastroPet() {
        initComponents();
    }
    
    //Metodo construtor recebendo o usuario logado
    public CadastroPet(Usuario usuario) {
        initComponents();
        this.usuarioLogado = usuario; 
        
        //Carregando as especies para usar no combobox
        carregarEspecies();
    }
    
    private void carregarEspecies() {
        //Limpando quaisquer items que tiver no ComboBox
        cbEspeciePet.removeAllItems();

        //Buscando as especies disponiveis no Banco de dados usando o EspecieDAO
        EspecieDAO dao = new EspecieDAO(); 
        ArrayList<Especie> especies = dao.listarEspecies();

        // Adiciona as espécies no ComboBox
        for (Especie especie : especies) {
            cbEspeciePet.addItem(especie);
        }
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCadastroPet = new javax.swing.JPanel();
        jlNomePet = new javax.swing.JLabel();
        txtNomePet = new javax.swing.JTextField();
        jlIdadePet = new javax.swing.JLabel();
        txtIdadePet = new javax.swing.JTextField();
        jlStatusPet = new javax.swing.JLabel();
        cbStatusPet = new javax.swing.JComboBox<>();
        jlEspeciePet = new javax.swing.JLabel();
        cbEspeciePet = new javax.swing.JComboBox<>();
        btnCadastrarPet = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastrar Pets");

        jlNomePet.setText("Nome do Pet");

        txtNomePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomePetActionPerformed(evt);
            }
        });

        jlIdadePet.setText("Idade ");

        txtIdadePet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdadePetActionPerformed(evt);
            }
        });

        jlStatusPet.setText("Status ");

        cbStatusPet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "disponivel", "adotado" }));

        jlEspeciePet.setText("Espécie");

        btnCadastrarPet.setText("Cadastrar");
        btnCadastrarPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarPetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpCadastroPetLayout = new javax.swing.GroupLayout(jpCadastroPet);
        jpCadastroPet.setLayout(jpCadastroPetLayout);
        jpCadastroPetLayout.setHorizontalGroup(
            jpCadastroPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroPetLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jpCadastroPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlEspeciePet)
                    .addComponent(jlStatusPet)
                    .addComponent(jlIdadePet)
                    .addComponent(txtIdadePet)
                    .addComponent(jlNomePet)
                    .addComponent(txtNomePet)
                    .addComponent(cbStatusPet, 0, 400, Short.MAX_VALUE)
                    .addComponent(cbEspeciePet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpCadastroPetLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnCadastrarPet)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jpCadastroPetLayout.setVerticalGroup(
            jpCadastroPetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroPetLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jlNomePet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomePet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlIdadePet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIdadePet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlStatusPet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbStatusPet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlEspeciePet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbEspeciePet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrarPet)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCadastroPet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCadastroPet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomePetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomePetActionPerformed

    private void txtIdadePetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadePetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadePetActionPerformed

    private void btnCadastrarPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarPetActionPerformed
        // TODO add your handling code here:
        //Recebendo os valores 
        String nome = txtNomePet.getText();
        String idadeTexto = txtIdadePet. getText(); //Definindo idade texto, pois depois faremos a validacao se o usuario enviou um numero
        String status = cbStatusPet.getSelectedItem().toString();
        
        //Validando se o usuario deixou campos em vazio
        if (nome.isEmpty() || idadeTexto.isEmpty()) {
            //Se tiver em branco vai lancar uma msg
            JOptionPane.showMessageDialog(this, "Preencha todos os campos!");
            return;
        }
        
        //Validando se o usuario selecionou uma especie
        if (cbEspeciePet. getSelectedItem() == null) {
            //Se tiver em branco vai lancar uma msg
            JOptionPane.showMessageDialog(this, "Selecione uma espécie!");
            return;
        }
        
        //Pegando o valor da especie selecionada
        Especie especieSelecionada = (Especie) cbEspeciePet.getSelectedItem();
        
        //Validando se o usuario inseriu um numero no campo de idade
        int idade;
        try {
            idade = Integer.parseInt(idadeTexto);
            if (idade < 0) {
                //Impedindo com o que o usuario esteja inserindo um numero valido
                JOptionPane.showMessageDialog(this, "A idade deve ser um número positivo!");
                return;
            }
        } catch (NumberFormatException ex) {
            //Se o usuario tentar inserir caracteres diferente de numero vai dar erro.
            JOptionPane.showMessageDialog(this, "A idade deve ser um número válido!");
            return;
        }
        
        //Criando o objeto pet e armazenando os valores recebidos pelo usuario
        Pet pet = new Pet();
        pet.setNomePet(nome);
        pet. setIdadePet(idade);
        pet.setStatusPet(status);
        pet.setIdUsuarioDono(usuarioLogado.getIdUsuario()); //ID do usuarioLogado
        pet.setIdEspecie(especieSelecionada.getIdEspecie()); //ID da especie selecionada
        
        //Pegando os valores armazenados e guardando no banco de dados utilizando o PetDAO
        PetDAO dao = new PetDAO();
        
        if (dao.create(pet)) {
            //Caso de certo ele vai cadastrar
            JOptionPane.showMessageDialog(this, "Pet cadastrado com sucesso!");
            
            //Depois da insercao ele vai limpar os campos
            txtNomePet.setText("");
            txtIdadePet.setText("");
            cbStatusPet.setSelectedIndex(0);
            if (cbEspeciePet.getItemCount() > 0) {
                cbEspeciePet. setSelectedIndex(0);
            }
            
        } else {
            //Se tiver erro, ele vai lancar erro
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar pet!");
        }
    }//GEN-LAST:event_btnCadastrarPetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarPet;
    private javax.swing.JComboBox<Especie> cbEspeciePet;
    private javax.swing.JComboBox<String> cbStatusPet;
    private javax.swing.JLabel jlEspeciePet;
    private javax.swing.JLabel jlIdadePet;
    private javax.swing.JLabel jlNomePet;
    private javax.swing.JLabel jlStatusPet;
    private javax.swing.JPanel jpCadastroPet;
    private javax.swing.JTextField txtIdadePet;
    private javax.swing.JTextField txtNomePet;
    // End of variables declaration//GEN-END:variables
}
