/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.bean.Especie;
import model.bean.Interesse;
import model.bean.Pet;
import model.bean.Usuario;
import model.dao.EspecieDAO;
import model.dao.InteresseDAO;
import model.dao.PetDAO;

/**
 *
 * @author nicol
 */
public class ListarPets extends javax.swing.JInternalFrame {
    //Variavel para manter o usuario logado
    private Usuario usuarioLogado;
    
    /**
     * Creates new form ListarPets
     */
    public ListarPets() {
        initComponents();
    }
    
    //Iniciando um construtor recebendo o usuario logado
    public ListarPets(Usuario usuario) {
        initComponents();
        this.usuarioLogado = usuario;
        
        //Se o usuario for doador, o botao de solicitar adocao vai ser desabilitado
        if (usuarioLogado.getTipoUsuario().equalsIgnoreCase("doador")) {
            btnSolicitarAdocao.setEnabled(false);
            btnSolicitarAdocao.setVisible(false);
        }
        
        //Carregando os pets disponiveis na tabela
        carregarPets();
    }
    
    //Criando um metodo para carregar os pets na tela
    private void carregarPets() {
        //Buscando os pets no banco de dados
        PetDAO dao = new PetDAO();
        ArrayList<Pet> pets = dao.listarPets();
        
        //Configurando o modelo da tabela
        DefaultTableModel modelo = (DefaultTableModel) tableListarPets.getModel();
        modelo.setRowCount(0); //Limpando a tabela
        
        //Incluindo os pets dinamicamente na tabela
        for (Pet pet : pets) {
            modelo. addRow(new Object[]{
                pet.getIdPet(),
                pet.getNomePet(),
                pet.getIdadePet() + " anos",
                obterNomeEspecie(pet.getIdEspecie()),
                pet.getStatusPet()
            });
        }
    }
    
    //Metodo auxiliar criado para buscar o nome da especie
    private String obterNomeEspecie(int idEspecie) {
        // Por enquanto, vamos retornar o ID
        EspecieDAO dao = new EspecieDAO();
        ArrayList<Especie> especies = dao.listarEspecies();
        
        for (Especie especie : especies) {
            if (especie.getIdEspecie() == idEspecie) {
                return especie.getNomeEspecie();
            }
        }
        
        //Caso de errado, vai retornar uma mensagem
        return "Espécie desconhecida!";
    }       
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListarPets = new javax.swing.JTable();
        btnSolicitarAdocao = new javax.swing.JButton();

        setClosable(true);
        setTitle("Listar Pets");

        tableListarPets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome Pet", "Idade", "Espécie", "Status"
            }
        ));
        jScrollPane1.setViewportView(tableListarPets);

        btnSolicitarAdocao.setText("Solicitar Adoção");
        btnSolicitarAdocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarAdocaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addComponent(btnSolicitarAdocao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSolicitarAdocao)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolicitarAdocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarAdocaoActionPerformed
        // TODO add your handling code here:
        //Verificando se o usuario selecionou alguma linha da tabela
        int linhaSelecionada = tableListarPets.getSelectedRow();
        
        //Usando if para verificar se nao tem nenhuma tabela selecionada, se nao tiver vai lancar uma mensagem
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, 
                "Por favor, selecione um pet para solicitar adoção!", 
                "Atenção", 
                JOptionPane. WARNING_MESSAGE);
            return;
        }
        
        //Pegando o id do pet selecionado pelo usuario
        int idPet = (int) tableListarPets.getValueAt(linhaSelecionada, 0);
        String nomePet = (String) tableListarPets.getValueAt(linhaSelecionada, 1);
        
        //Confirmando se o usuario ja informou interesse(solicitou adocao) nesse pet
        InteresseDAO interesseDAO = new InteresseDAO();
        if (interesseDAO.verificarInteresseExistente(idPet, usuarioLogado.getIdUsuario())) {
            JOptionPane.showMessageDialog(this,
                "Você já solicitou adoção em " + nomePet + "!",
                "Aviso",
                JOptionPane. WARNING_MESSAGE);
            return;
        }
                
        //Confirmando se o usuario realmente deseja solicitar uma adocao
        int confirmacao = JOptionPane.showConfirmDialog(this,
            "Deseja solicitar a adoção de " + nomePet + "? ",
            "Confirmar Adoção",
            JOptionPane.YES_NO_OPTION);
        
        //Se ele confirmar essa solicitacao
        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                //Cria um objeto interesse com os dados do usuario e do pet
                Interesse interesse = new Interesse();
                interesse.setIdPet(idPet);
                interesse.setIdUsuario(usuarioLogado.getIdUsuario());
                
                //Registrando o interesse(solicitacao) no banco de dados
                if(interesseDAO.registrarInteresse(interesse)) {
                    //Se der certo, vai mostrar mensagem de sucesso
                    JOptionPane.showMessageDialog(this,
                        "Interesse em " + nomePet + " registrado com sucesso!\n" +
                        "O doador será notificado e entrará em contato.",
                        "Sucesso",
                        JOptionPane.INFORMATION_MESSAGE);
                    
                    //Recarregando a lista de pets
                    carregarPets();
                } else {
                    //Se der erro, mostra mensagem de erro
                    JOptionPane.showMessageDialog(this,
                        "Erro ao registrar interesse.  Tente novamente.",
                        "Erro",
                        JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this,
                    "Erro ao registrar interesse: " + ex. getMessage(),
                    "Erro",
                    JOptionPane. ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSolicitarAdocaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSolicitarAdocao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableListarPets;
    // End of variables declaration//GEN-END:variables
}
