/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package views;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import model.bean.Pet;
import model.bean.Usuario;
import model.dao.PetDAO;

/**
 *
 * @author nicol
 */
public class ListarPets extends javax.swing.JInternalFrame {
    //Variavel para manter o usuario logado
    private Usuario usuarioLogado;
    
    /**
     * Creates new form ListarPets
     */
    public ListarPets() {
        initComponents();
    }
    
    //Iniciando um construtor recebendo o usuario logado
    public ListarPets(Usuario usuario) {
        initComponents();
        this.usuarioLogado = usuario;
        
        //Carregando os pets disponiveis na tabela
        carregarPets();
    }
    
    //Criando um metodo para carregar os pets na tela
    private void carregarPets() {
        //Buscando os pets no banco de dados
        PetDAO dao = new PetDAO();
        ArrayList<Pet> pets = dao.listarPets();
        
        //Configurando o modelo da tabela
        DefaultTableModel modelo = (DefaultTableModel) tableListarPets.getModel();
        modelo.setRowCount(0); //Limpando a tabela
        
        //Incluindo os pets dinamicamente na tabela
        for (Pet pet : pets) {
            modelo. addRow(new Object[]{
                pet.getIdPet(),
                pet.getNomePet(),
                pet.getIdadePet() + " anos",
                obterNomeEspecie(pet.getIdEspecie()),
                pet.getStatusPet()
            });
        }
    }
    
    //Metodo auxiliar criado para buscar o nome da especie
    private String obterNomeEspecie(int idEspecie) {
        // Você pode melhorar isso buscando direto do banco
        // Por enquanto, vamos retornar o ID
        PetDAO dao = new PetDAO();
        ArrayList<model.bean.Especie> especies = dao.listarEspecies();
        
        for (model.bean.Especie especie : especies) {
            if (especie.getIdEspecie() == idEspecie) {
                return especie.getNomeEspecie();
            }
        }
        
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListarPets = new javax.swing.JTable();
        btnSolicitarAdocao = new javax.swing.JButton();

        setClosable(true);
        setTitle("Listar Pets");

        tableListarPets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome Pet", "Idade", "Espécie", "Status"
            }
        ));
        jScrollPane1.setViewportView(tableListarPets);

        btnSolicitarAdocao.setText("Solicitar Adoção");
        btnSolicitarAdocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitarAdocaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                    .addComponent(btnSolicitarAdocao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSolicitarAdocao)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSolicitarAdocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitarAdocaoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSolicitarAdocaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSolicitarAdocao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableListarPets;
    // End of variables declaration//GEN-END:variables
}
