/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import model.bean.Usuario;

/**
 *
 * @author nicol
 */
public class TelaPrincipal extends javax.swing.JFrame {
    //Criando a variavel de usuario logado
    private Usuario usuarioLogado;
    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }
    
    //Iniciando um metodo construtor
    public TelaPrincipal(Usuario usuario) {
        initComponents();
        this.usuarioLogado = usuario;
        
        //Dando boas vindas ao usuario
        this.setTitle("Sistema de Adoção - Olá, " + usuario.getNomeUsuario());
        
        //Diferenciando os usuario por tipo. adotante ou doador
        if ("doador".equals(usuario.getTipoUsuario())) {
            System.out. println("Usuário logado como DOADOR");
        } else if ("adotante".equals(usuario.getTipoUsuario())) {
            System.out.println("Usuário logado como ADOTANTE");
        }
    }
    
    //Metodo para acessar o usuario em outras partes do codigo
    public Usuario getUsuarioLogado() {
        return usuarioLogado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuPets = new javax.swing.JMenu();
        miCadastrarPet = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        MenuAdocao = new javax.swing.JMenu();
        miSolicitacaoAdocao = new javax.swing.JMenuItem();
        MenuPerfil = new javax.swing.JMenu();
        miSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 913, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        MenuPets.setText("Pets");

        miCadastrarPet.setText("Cadastrar Pet");
        miCadastrarPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastrarPetActionPerformed(evt);
            }
        });
        MenuPets.add(miCadastrarPet);

        jMenuItem2.setText("Gerenciar Solicitações");
        MenuPets.add(jMenuItem2);

        jMenuBar1.add(MenuPets);

        MenuAdocao.setText("Adoção");

        miSolicitacaoAdocao.setText("Listar Pets");
        miSolicitacaoAdocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSolicitacaoAdocaoActionPerformed(evt);
            }
        });
        MenuAdocao.add(miSolicitacaoAdocao);

        jMenuBar1.add(MenuAdocao);

        MenuPerfil.setText("Perfil");

        miSair.setText("Sair ");
        miSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSairActionPerformed(evt);
            }
        });
        MenuPerfil.add(miSair);

        jMenuBar1.add(MenuPerfil);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miSolicitacaoAdocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSolicitacaoAdocaoActionPerformed
        // TODO add your handling code here:
        ListarPets telaListarPets = new ListarPets(usuarioLogado);
        painelPrincipal.add(telaListarPets);
        telaListarPets.setVisible(true);
    }//GEN-LAST:event_miSolicitacaoAdocaoActionPerformed

    private void miSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSairActionPerformed
        // TODO add your handling code here:
        //Confirmando se o usuario deseja sair
        int resposta = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente sair?",
            "Confirmar Saída",
            javax.swing. JOptionPane.YES_NO_OPTION, //Oferecendo as opcoes de YES ou NO para o usuario
            javax.swing.JOptionPane. QUESTION_MESSAGE
        );
        
        //Se o usuario escolher a opcao YES
        if (resposta == javax.swing.JOptionPane.YES_OPTION) {
            //Vai abrir a tela de login
            Login telaLogin = new Login();
            telaLogin.setVisible(true);
            telaLogin.setLocationRelativeTo(null); //Centralizando o conteudo na tela

            //Fechando a tela princpal
            this.dispose();
        }
    }//GEN-LAST:event_miSairActionPerformed

    private void miCadastrarPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastrarPetActionPerformed
        // TODO add your handling code here:
        //Criando a tela de cadastro de pets para o usuario logado
        CadastroPet telaCadastroPet = new CadastroPet(usuarioLogado);
        painelPrincipal.add(telaCadastroPet);
        telaCadastroPet.setVisible(true);
    }//GEN-LAST:event_miCadastrarPetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Configura o look and feel Nimbus (opcional) */
        try {
            for (javax.swing.UIManager. LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing. UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level. SEVERE, null, ex);
        }

        /* Cria e exibe a tela de Login */
        java.awt.EventQueue. invokeLater(new Runnable() {
            public void run() {
                Login telaLogin = new Login();
                telaLogin.setVisible(true);
                telaLogin. setLocationRelativeTo(null); //Centraliza na tela
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuAdocao;
    private javax.swing.JMenu MenuPerfil;
    private javax.swing.JMenu MenuPets;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem miCadastrarPet;
    private javax.swing.JMenuItem miSair;
    private javax.swing.JMenuItem miSolicitacaoAdocao;
    private javax.swing.JDesktopPane painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
